- name: stop nginx 
  shell: sudo systemctl stop nginx 

- name: run certbot
  shell: certbot --authenticator standalone --installer nginx -d shop.mbrien.net --email martin@mbrien.net --agree-tos -n --redirect

- name: strat nginx
  shell: sudo systemctl start nginx
