- name: Shiny service unit file
  file: src='/home/martin/tarsnap/dotfiles/{{item}}.service' dest='/usr/lib/systemd/system/{{item}}.service' state=link
  with_items:
       - sampleshiny
       - wagewonk
  become: true 

- name: start services           # start services
  shell: systemctl enable --now "{{item}}".service
  with_items:
     - sampleshiny
     - wagewonk
  become: true

- name: start services           # start services
  shell: systemctl restart "{{item}}".service
  with_items:
     - sampleshiny
     - wagewonk
  become: true

